# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

# trigger:
# - main

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'

- script: 'sudo softwareupdate --install-rosetta --agree-to-license'
  displayName: 'Accept License'

- script: 'brew install openjdk@17'
  displayName: 'Install Java'

- script: |
    flutter --disable-analytics
    flutter build apk
